;this file for FamiTone2 libary generated by FamiStudio

_PauseBeep:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_song_1

@sfx_ntsc_song_1:
	.byte $82,$00,$81,$6a,$80,$35,$89,$f0,$01,$81,$12,$80,$33,$01,$81,$13
	.byte $02,$81,$23,$80,$32,$01,$82,$01,$81,$3f,$80,$34,$07,$00

.export _PauseBeep
